### ISSUE TITLE
Function Error 

### ISSUE THREAD

**Issue by arbazkiraak** [sethsec/Nodejs-SSRF-App#1]
nodejs  ssrf-demo-app.js -p 8080
/var/www/html/Nodejs-SSRF-App/ssrf-demo-app.js:19
var options = cli.parse()
                  ^

TypeError: cli.parse is not a function
    at Object.<anonymous> (/var/www/html/Nodejs-SSRF-App/ssrf-demo-app.js:19:19)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:134:18)
    at node.js:962:3

**Comment by sethsec** [comment]
Yea. i was able to reproduce on kali.  Not sure why it stopped working, but i changed the command line portion to match the documentation at https://www.npmjs.com/package/command-line-args.  Now it works again.  Let me know if this fixes your issue!

**Comment by arbazkiraak** [comment]
Hey @sethsec ,

Thanks For the Commit , 

nodejs ssrf-demo-app.js -p 80

##################################################
#

# Server listening for connections on port:80

# Connect to server using the following url:

# -- http://[server]:80/?url=[SSRF URL]

#
##################################################
New request: /
TypeError: URL must be a string, not undefined
    at new Needle (/var/www/html/ssrf/Nodejs-SSRF-App/node_modules/needle/lib/needle.js:124:11)
    at Object.exports.(anonymous function) [as get](/var/www/html/ssrf/Nodejs-SSRF-App/node_modules/needle/lib/needle.js:651:12)
    at /var/www/html/ssrf/Nodejs-SSRF-App/ssrf-demo-app.js:32:12
    at Layer.handle [as handle_request](/var/www/html/ssrf/Nodejs-SSRF-App/node_modules/express/lib/router/layer.js:95:5)
    at next (/var/www/html/ssrf/Nodejs-SSRF-App/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/var/www/html/ssrf/Nodejs-SSRF-App/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request](/var/www/html/ssrf/Nodejs-SSRF-App/node_modules/express/lib/router/layer.js:95:5)
    at /var/www/html/ssrf/Nodejs-SSRF-App/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (/var/www/html/ssrf/Nodejs-SSRF-App/node_modules/express/lib/router/index.js:330:12)
    at next (/var/www/html/ssrf/Nodejs-SSRF-App/node_modules/express/lib/router/index.js:271:10)

Kali 2.0 2016

**Comment by sethsec** [comment]
Yea, not the most robust demo app.  You have to put the url parameter name and value in for it to work.  

```
sudo nodejs ssrf-demo-app.js -p 8080
http://<ip of your kali box>:8080/?url=http://ifconfig.pro
```

**Comment by arbazkiraak** [comment]
Hey Thanks @sethsec  :) 

:100: I Appreciate your Efforts :+1:
